### ISSUE TITLE
need readme or tutorial to use

### ISSUE THREAD

**Issue by nightmare04** [AntonTumilovich/https-flows.nodered.org-node-node-red-contrib-yandex-alice-command#1]
Просто не понятно как пользоваться, ввел данные аккаунта от Яндекса, в лог выпадает что не авторизирован, и куча ошибок сверху.

**Comment by nightmare04** [comment]
О, выключил двухфакторную авторизацию, сработало... но это не отменяет необходимость readme

**Comment by AntonTumilovich** [comment]
Да с двух факторной не работает. Увы, на документацию, нет времени, если есть желание помочь с документацией - велкам )

**Comment by AntonTumilovich** [comment]
Один добрый человек написал мануал :
https://wiki.yaboard.com/w/Таймеры,_несколько_команд_устройству,_TTS_(Node-RED)

**Comment by guinmoon** [comment]
Спасибо за модуль! Двухфакторка работает, нужно успеть ввести одноразовый пароль из приложения Яндекс.Ключ, а затем использовать куки.

**Comment by AntonTumilovich** [comment]
> Спасибо за модуль! Двухфакторка работает, нужно успеть ввести одноразовый пароль из приложения Яндекс.Ключ, а затем использовать куки.
Пожалуйста!
Не могли бы вы подробнее описать весь порядок действия ?

**Comment by guinmoon** [comment]
> > Спасибо за модуль! Двухфакторка работает, нужно успеть ввести одноразовый пароль из приложения Яндекс.Ключ, а затем использовать куки.
> > Пожалуйста!
> > Не могли бы вы подробнее описать весь порядок действия ?

Выход alice_send ноды соединяем с debug для получения cookies, speaker_id и scenario_id.
В поле Username указываем имя пользователя yandex (я указывал без @). В поле Password указываем одноразовый пароль из приложения Я.Ключ (обновляется каждые 30 секунд). 
Если все указали правильно то в дебаге увидим все три поля.
