### ISSUE TITLE
StatusCodeError: 401 - "Unauthorized\n

### ISSUE THREAD

**Issue by midnight1979** [AntonTumilovich/https-flows.nodered.org-node-node-red-contrib-yandex-alice-command#10]
Не проходит авторизацию соответственно не получает колонки из аккаунта

**Comment by midnight1979** [comment]
Пообщавшись с автором выяснили предварительно что авторизации мешают спецсимволы: @$

**Comment by algar42** [comment]
Unauthorized\n, да. Спецсимволов нету. 
Причем пару месяцев назад нода работала с теми же параметрами авторизации

**Comment by AntonTumilovich** [comment]
Обновил, теперь должно работать с любыми символами и добавил информацию по альтернативному получению cookies.

**Comment by Anzic23** [comment]
Та же ошибка. Альтернативный метод не работает, такой запрос просто не появляется в панели разработчика.
