### ISSUE TITLE
как настроить ноду, если установлена двухфактораня авторизация на учетной записи yanex

### ISSUE THREAD

**Issue by decole** [AntonTumilovich/https-flows.nodered.org-node-node-red-contrib-yandex-alice-command#13]
Поставил данную ноду к себе. Есть 2 колонки irbis A. 
Напишите пожалуйста как завезти это чудо.
можете предоставить json экспорт простой схемы сценария ?
что должно быть в топике и payload в элементе inject?

добавил coockies из ссылки на /iot добавил идентификатор колонки из настроек.
в инжекте в payload поставил тескт, который хочу чтобы колонка сказала.
в итоге колонка молчит

**Comment by gonzzzales** [comment]
тоже перестала говорить. не пойму в чем дело. два дня назад говорила и вдруг перестала. Все куки, id колонки вбиты

**Comment by decole** [comment]
Яндекс поменял апи запросы или еще что-то. Печаль, будем ждать фикса, возможно кто-нибудь поможет

**Comment by DmitrySlav** [comment]
Та же проблема.

**Comment by AntonTumilovich** [comment]
#14
