### ISSUE TITLE
Настройка и использование

### ISSUE THREAD

**Issue by ptath** [AntonTumilovich/https-flows.nodered.org-node-node-red-contrib-yandex-alice-command#15]
Не получается запустить, вообще.

Установил ноду, в настройках прописал логин, пароль, кукисы, включил дебаг. С неправильным логином, паролем или кукисами ругается, без них нет. Но и ничего не происходит, совершенно, при отправлении текста или команды. Инжект стринг, дебаг всех сообщений.

В дебаге сообщения типа:

 ```
{"payload":"Get csrf token: begin","_msgid":"603b43ab6bdd8fba"}
{"payload":"Get csrf token: ok","_msgid":"4721535be8c38ba2"}
{"payload":"Get devices: begin","_msgid":"242c764ce54583fb"}
{"payload":"Get devices: ok","_msgid":"1c3026d4deca9036"}
{"payload":"Get devices: found speaker Станция Мини new 6537, id: 556d7176-d49c-4b23-8128-1aeceb0fd478","_msgid":"7a94066f6df42b21"}

... Get/add scenarios: begin/ok ... 

{"payload":"Show all data: ok","_msgid":"ded761c13e8dc751"}

{"_msgid":"9f18cd632d048ea4","payload":"{\"cookies\":\"_yasc=D++arMuХХХХХХХХХХ; Silicon=1; Session_id=ХХХХХХХХХ; sessionid2=ХХХХХХХХХХХХХХХ; yandex_login=ptath; is_gdpr=0; is_gdpr_b=ХХХХХХХХХХХ; i=}
```

И на этом все заканчивается. Куда смотреть?

**Comment by AntonTumilovich** [comment]
Добрый день, Яндекс постоянно меняет API Алисы, а у меня сейчас нет времени заниматься проектом, но вот форк моего проекта с актуальным Яндекс.Алиса API
https://github.com/ksrt12
