### ISSUE TITLE
Add scenarios: fail StatusCodeError: 403 - "Forbidden\n

### ISSUE THREAD

**Issue by vvzvlad** [AntonTumilovich/https-flows.nodered.org-node-node-red-contrib-yandex-alice-command#16]
При попытке заставить алису произнести что-то, получаю при включенном дебаге вот такую ошибку. 
```
Get csrf token: begin
Get csrf token: ok
Get scenarios: begin
Get scenarios: ok
Add scenario: begin
Add scenarios: fail StatusCodeError: 403 - "Forbidden\n"
Show all data: ok
{"cookies":"{cookies:yandexuid=...skipped....;}"}
```

**Comment by AntonTumilovich** [comment]
Добрый день, Яндекс постоянно меняет API Алисы, а у меня сейчас нет времени заниматься проектом, но вот форк моего проекта с актуальным Яндекс.Алиса API
https://github.com/ksrt12
