### ISSUE TITLE
залипание при наличии нескольких колонок

### ISSUE THREAD

**Issue by Bigmanekb** [AntonTumilovich/https-flows.nodered.org-node-node-red-contrib-yandex-alice-command#2]
В настоящее время стоит две колонки Irbis и Станция Мини

с ирбисом все окей, а вот со станцией все плохо. Она сутки отработала нормально, как в индивидуальном режиме, так и при работе без указания ID колонок, а потом она стала залипать.

Залипание выглядит так:

отправляем один TTS - она его произносит, отправляем другой, а она произносит первый... при отправке на несколько колонок она вообще молчит.

в общем с мини все непросто и выловить что является причиной невозможно.

**Comment by AntonTumilovich** [comment]
Если использовать несколько колонок своими потоками, лучше создать для каждой колонки свои логин и прописать в эти лосинах разные имена сценариев
