### ISSUE TITLE
Перестали обновляться сценарии.

### ISSUE THREAD

**Issue by bttrem** [AntonTumilovich/https-flows.nodered.org-node-node-red-contrib-yandex-alice-command#4]
Похоже API у Яндекса поменялись. После запуска alice-send в целевом сценарии пусто.
Ещё заметил что если запускать сценарий не голосом, а кнопкой в приложении - не работают команды и TTS. При этом управление устройствами функционирует. У меня Irbis A с облачным управлением.
[Здесь](https://github.com/AlexxIT/YandexStation/issues/45) кое что есть на эту тему.

Проблемы появились 3.08.2020. До того работало отлично, за что вам большое спасибо.

**Comment by AntonTumilovich** [comment]
Добрый день. Вечером буду чинить.

**Comment by AntonTumilovich** [comment]
Исправлено в версии 1.15 от 05/08/20
