### ISSUE TITLE
Is there any way to deal with two factor autentification?

### ISSUE THREAD

**Issue by dmitrymoshalkov** [AntonTumilovich/https-flows.nodered.org-node-node-red-contrib-yandex-alice-command#6]
Does it possible to use this node with two factor autentification?

**Comment by AntonTumilovich** [comment]
Hi, look [this](https://github.com/AntonTumilovich/https-flows.nodered.org-node-node-red-contrib-yandex-alice-command/issues/1#issuecomment-734454233)

**Comment by dmitrymoshalkov** [comment]
> Hi, look [this](https://github.com/AntonTumilovich/https-flows.nodered.org-node-node-red-contrib-yandex-alice-command/issues/1#issuecomment-734454233)

Thank you!
