### ISSUE TITLE
TTS error

### ISSUE THREAD

**Issue by vladtsit** [AntonTumilovich/https-flows.nodered.org-node-node-red-contrib-yandex-alice-command#8]
Ни с того, ни с его сломалась алиса, редеплой и перезапуск не помагает

"Alice:error:update:scenarios:StatusCodeError: 400 - "{"request_id":"40af0791-d800-4f12-8fc2-6e88b589aca8","status":"error","code":"INVALID_VALUE"}""
Возникает в момент, когда я шлю TTS команду, при этом она произносит предыдущий текст, а не тот, что я отправил.
Чудеса какие-то.
Команды работают нормально.

Есть идеи что с этим сделать?

**Comment by AntonTumilovich** [comment]
Обновитесь до 1.18, должно заработать

**Comment by vladtsit** [comment]
Спасибо, заработало!

**Comment by AntonTumilovich** [comment]
> Спасибо, заработало!

Пожалуйста )
