### ISSUE TITLE
"Потерял" 1 из 4 колонок

### ISSUE THREAD

**Issue by semikor** [AntonTumilovich/https-flows.nodered.org-node-node-red-contrib-yandex-alice-command#9]
Приветствую, Антон!
Вчера 8.04.21 приблизительно с 16 часов потерялась одна из четырех колонок в node-red (каждая со своим аккаунтом, т.е. 4 отдельных аккаунта Яндекса). Никаких особых манипуляций не производил.
Дебаг выводит с одного обращения по порядку:

Get cookies: begin
Get cookies: stage 2: begin
Get cookies: stage 2: end
Get csrf token: begin
Get csrf token: ok
Get devices: begin
TypeError: Cannot read property 'length' of undefined
Get devices: fail StatusCodeError: 401 - "Unauthorized\n"
Get devices: error: no devices in account
Get devices: error: no devices in account
Get devices: error: no speaker in account
Get scenarios: begin
TypeError: Cannot read property 'length' of undefined
Get scenarios: fail StatusCodeError: 401 - "Unauthorized\n"
Get scenarios: no scenarios in account
Add scenario: begin
Add scenarios: fail StatusCodeError: 401 - "Unauthorized\n"
undefined

Аккаунт в NR обновлял, NR перезапускал. Колонку сбрасывал, переподключал к яндексу и после этого опять переподключал аккаунт в NR и перезагружал. "Выходил из всех устройств" в Я.аккаунте и заново всё подключал, вводил, перезагружал... )) не знаю, чего еще придумать...
Остальные 3 колонки со своими аккаунтами как работали - так и работают.
Подскажите, пожалуйста, что можно сделать, чтобы восстановить работу!
Спасибо!
Сергей.

**Comment by hollligan** [comment]
тоже самое и у меня, только потерял две из двух колонок.
По дебагу один в один ваша проблема.

**Comment by semikor** [comment]
У меня оказалось, что дочь в своем аккаунте яндекса поставила галочку подтверждения входа по телефону, снял галочку - всё восстановилось.

**Comment by AntonTumilovich** [comment]
> тоже самое и у меня, только потерял две из двух колонок.
> По дебагу один в один ваша проблема.

Добрый день.
проверьте что аккаунт который вы подключаете не имеет 2х факторной авторизации и прочих заморочек при логине и попробуйте заново создать конект к Алисе с этим аккаунтом
